# Generated by Django 4.2.6 on 2023-11-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('imgSmall', models.ImageField(upload_to='images/')),
                ('imgLg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
