# Generated by Django 4.2.6 on 2024-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgageadvisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('broker', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('isActive', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Catalogo Brokers',
            },
        ),
    ]
