# Generated by Django 4.2.6 on 2023-11-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('facebook', 'facebook'), ('twiter', 'twiter'), ('youtube', 'youtube'), ('phone', 'Teléfono'), ('whatsapp', 'whatsapp'), ('linkedin', 'linkedin')], max_length=20)),
                ('link', models.CharField(max_length=50)),
                ('isActive', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Red Social',
            },
        ),
    ]
