# Generated by Django 4.2.6 on 2023-11-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('facebook', 'facebook'), ('twitter', 'twitter'), ('youtube', 'youtube'), ('phone', 'Teléfono'), ('whatsapp', 'whatsapp'), ('linkedin', 'linkedin')], max_length=20),
        ),
    ]
