# Generated by Django 4.2.6 on 2023-11-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('headerColor', models.CharField(max_length=100)),
                ('tileColor', models.CharField(max_length=50)),
                ('titleSize', models.CharField(max_length=20)),
                ('subTitleColor', models.CharField(max_length=20)),
                ('subTitleSize', models.CharField(max_length=20)),
                ('titleBySecctionColor', models.CharField(max_length=20)),
                ('titleBySecctionSize', models.CharField(max_length=20)),
                ('titleBySecctionAlign', models.CharField(choices=[('izquierda', 'izquierda'), ('centrado', 'centrado'), ('derecha', 'derecha')], max_length=30)),
                ('colorFooter', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tema',
            },
        ),
    ]
